# Generated by Django 2.0.2 on 2018-02-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platillo', models.CharField(max_length=30)),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grasa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybarapp.Platillo')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('ruc_res_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('restaurante', models.CharField(max_length=30)),
                ('facultad', models.CharField(max_length=30)),
                ('horario_ini', models.TimeField()),
                ('horario_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Typos_usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_real', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_reserva', models.DateTimeField()),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybarapp.Precio')),
            ],
        ),
        migrations.AddField(
            model_name='typos_usuarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybarapp.Usuario'),
        ),
        migrations.AddField(
            model_name='precio',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybarapp.Restaurante'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybarapp.Precio'),
        ),
    ]
