# Generated by Django 2.0.2 on 2018-02-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platillo', models.CharField(max_length=30)),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grasa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(choices=[(0, 'Cero Estrella'), (1, 'Una Estrella'), (2, 'Dos Estrellas'), (3, 'Tres Estrellas'), (4, 'Cuatro Estrellas'), (5, 'Cinco Estrellas')], default=0)),
                ('precio', models.FloatField()),
                ('comentario', models.TextField()),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybarapp.Platillo')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('ruc_res_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('restaurante', models.CharField(max_length=30)),
                ('facultad', models.CharField(max_length=30)),
                ('horario_ini', models.TimeField()),
                ('horario_fin', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='precio',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybarapp.Restaurante'),
        ),
    ]
