# Generated by Django 2.0.2 on 2018-02-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
