# Generated by Django 2.0.2 on 2018-02-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platillo',
            options={'ordering': ['platillo']},
        ),
        migrations.AlterModelOptions(
            name='restaurante',
            options={'ordering': ['restaurante']},
        ),
    ]
