# Generated by Django 2.0.2 on 2018-02-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybarapp', '0003_auto_20180216_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='image',
            field=models.ImageField(upload_to='media/platillos/'),
        ),
    ]
